# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
        mkdir jar && cp target/*.jar jar
    
    - name: Upload Jar Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Jar
        path: jar
        
    - name: Create JavaDoc   
      run: |
        mvn javadoc:javadoc
        mkdir docs && cp -a target/site/apidocs docs
    
    - name: Upload JavaDocs artifact
      uses: actions/upload-artifact@v2
      with:
        name: Docs
        path: docs

    - name: Deploy JavaDoc
      uses: peaceiris/actions-gh-pages@v3
      # only deploy javaDoc on master branch
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/apidocs
    
    - name: Sonarcloud analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

