# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: mkdir jar && cp target/*.jar jar
    - uses: actions/upload-artifact@v2
      with:
        name: Jar
        path: jar
        
    - run: mvn javadoc:javadoc
    - run: mkdir docs && cp -a target/site/apidocs docs
    - uses: actions/upload-artifact@v2
      with:
        name: Docs
        path: docs


    - run: tar cfv apidocs.tar target/site/apidocs 
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
         
    - run: tar xfv apidocs.tar 
    - run: git commit -a
    - run: git push
   
